name = "BrazilianPowerModels"
uuid = "437be1c9-48e7-4aae-afd3-8e19dd3ac5b9"
authors = ["Iago Chavarry <iagochavarry@lampsco.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
